package com.infantstudio.community.Lists;

import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.support.v4.view.MenuItemCompat;
import android.support.v7.app.AppCompatActivity;
import android.support.v7.widget.SearchView;
import android.view.LayoutInflater;
import android.view.Menu;
import android.view.MenuItem;
import android.view.View;
import android.view.ViewGroup;
import android.widget.AdapterView;
import android.widget.BaseAdapter;
import android.widget.ListView;
import android.widget.TextView;

import com.infantstudio.community.Countrylist.FragmentCountryList;
import com.infantstudio.community.R;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

public class SearchProfestion extends AppCompatActivity {

    private ListView listView;
    private MyAppAdapter myAppAdapter;
    private ArrayList<SearchCountryPojo> postArrayList;
    public String value;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.search_city);
        listView= (ListView) findViewById(R.id.listView);
        postArrayList=new ArrayList<>();
        postArrayList.add(new SearchCountryPojo("Accountant"));
        postArrayList.add(new SearchCountryPojo("AccountsAssistant"));
        postArrayList.add(new SearchCountryPojo("AccountsClerk"));
        postArrayList.add(new SearchCountryPojo("AccountsManager"));
        postArrayList.add(new SearchCountryPojo("AccountsStaff"));
        postArrayList.add(new SearchCountryPojo("AcousticEngineer"));
        postArrayList.add(new SearchCountryPojo("Actor"));
        postArrayList.add(new SearchCountryPojo("Actress"));
        postArrayList.add(new SearchCountryPojo("Actuary"));
        postArrayList.add(new SearchCountryPojo("Acupuncturist"));
        postArrayList.add(new SearchCountryPojo("Adjustor"));
        postArrayList.add(new SearchCountryPojo("AdministrationAssistant"));
        postArrayList.add(new SearchCountryPojo("AdministrationClerk"));
        postArrayList.add(new SearchCountryPojo("AdministrationManager"));
        postArrayList.add(new SearchCountryPojo("AdministrationStaff"));
        postArrayList.add(new SearchCountryPojo("Administrator"));
        postArrayList.add(new SearchCountryPojo("AdvertisingAgent"));
        postArrayList.add(new SearchCountryPojo("AdvertisingAssistant"));
        postArrayList.add(new SearchCountryPojo("AdvertisingClerk"));
        postArrayList.add(new SearchCountryPojo("AdvertisingContractor"));
        postArrayList.add(new SearchCountryPojo("AdvertisingExecutive"));
        postArrayList.add(new SearchCountryPojo("AdvertisingManager"));
        postArrayList.add(new SearchCountryPojo("AdvertisingStaff"));
        postArrayList.add(new SearchCountryPojo("AerialErector"));
        postArrayList.add(new SearchCountryPojo("AerobicInstructor"));
        postArrayList.add(new SearchCountryPojo("AeronauticalEngineer"));
        postArrayList.add(new SearchCountryPojo("Agent"));
        postArrayList.add(new SearchCountryPojo("AirTrafficController"));
        postArrayList.add(new SearchCountryPojo("AircraftDesigner"));
        postArrayList.add(new SearchCountryPojo("AircraftEngineer"));
        postArrayList.add(new SearchCountryPojo("AircraftMaintenanceEngineer"));
        postArrayList.add(new SearchCountryPojo("AircraftSurfaceFinisher"));
        postArrayList.add(new SearchCountryPojo("Airman"));
        postArrayList.add(new SearchCountryPojo("AirportController"));
        postArrayList.add(new SearchCountryPojo("AirportManager"));
        postArrayList.add(new SearchCountryPojo("Almoner"));
        postArrayList.add(new SearchCountryPojo("AmbulanceController"));
        postArrayList.add(new SearchCountryPojo("AmbulanceCrew"));
        postArrayList.add(new SearchCountryPojo("AmbulanceDriver"));
        postArrayList.add(new SearchCountryPojo("AmusementArcadeWorker"));
        postArrayList.add(new SearchCountryPojo("Anaesthetist"));
        postArrayList.add(new SearchCountryPojo("Analyst"));
        postArrayList.add(new SearchCountryPojo("AnalyticalChemist"));
        postArrayList.add(new SearchCountryPojo("AnimalBreeder"));
        postArrayList.add(new SearchCountryPojo("Anthropologist"));
        postArrayList.add(new SearchCountryPojo("AntiqueDealer"));
        postArrayList.add(new SearchCountryPojo("ApplicationsEngineer"));
        postArrayList.add(new SearchCountryPojo("ApplicationsProgrammer"));
        postArrayList.add(new SearchCountryPojo("Arbitrator"));
        postArrayList.add(new SearchCountryPojo("Arborist"));
        postArrayList.add(new SearchCountryPojo("Archaeologist"));
        postArrayList.add(new SearchCountryPojo("Architect"));
        postArrayList.add(new SearchCountryPojo("Archivist"));
        postArrayList.add(new SearchCountryPojo("AreaManager"));
        postArrayList.add(new SearchCountryPojo("Armourer"));
        postArrayList.add(new SearchCountryPojo("Aromatherapist"));
        postArrayList.add(new SearchCountryPojo("ArtCritic"));
        postArrayList.add(new SearchCountryPojo("ArtDealer"));
        postArrayList.add(new SearchCountryPojo("ArtHistorian"));
        postArrayList.add(new SearchCountryPojo("ArtRestorer"));
        postArrayList.add(new SearchCountryPojo("Artexer"));
        postArrayList.add(new SearchCountryPojo("Artist"));
        postArrayList.add(new SearchCountryPojo("Arts"));
        postArrayList.add(new SearchCountryPojo("AssemblyWorker"));
        postArrayList.add(new SearchCountryPojo("Assessor"));
        postArrayList.add(new SearchCountryPojo("Assistant"));
        postArrayList.add(new SearchCountryPojo("AssistantCaretaker"));
        postArrayList.add(new SearchCountryPojo("AssistantCook"));
        postArrayList.add(new SearchCountryPojo("AssistantManager"));
        postArrayList.add(new SearchCountryPojo("AssistantNurse"));
        postArrayList.add(new SearchCountryPojo("AssistantTeacher"));
        postArrayList.add(new SearchCountryPojo("Astrologer"));
        postArrayList.add(new SearchCountryPojo("Astronomer"));
        postArrayList.add(new SearchCountryPojo("Attendant"));
        postArrayList.add(new SearchCountryPojo("AuPair"));
        postArrayList.add(new SearchCountryPojo("AuctionWorker"));
        postArrayList.add(new SearchCountryPojo("Auctioneer"));
        postArrayList.add(new SearchCountryPojo("Audiologist"));
        postArrayList.add(new SearchCountryPojo("AuditClerk"));
        postArrayList.add(new SearchCountryPojo("AuditManager"));
        postArrayList.add(new SearchCountryPojo("Auditor"));
        postArrayList.add(new SearchCountryPojo("AutoElectrician"));
        postArrayList.add(new SearchCountryPojo("AuxiliaryNurse"));
        postArrayList.add(new SearchCountryPojo("BaconCurer"));
        postArrayList.add(new SearchCountryPojo("BaggageHandler"));
        postArrayList.add(new SearchCountryPojo("Bailiff"));
        postArrayList.add(new SearchCountryPojo("Baker"));
        postArrayList.add(new SearchCountryPojo("BakeryAssistant"));
        postArrayList.add(new SearchCountryPojo("BakeryManager"));
        postArrayList.add(new SearchCountryPojo("BakeryOperator"));
        postArrayList.add(new SearchCountryPojo("Balloonist"));
        postArrayList.add(new SearchCountryPojo("BankClerk"));
        postArrayList.add(new SearchCountryPojo("BankManager"));
        postArrayList.add(new SearchCountryPojo("BankMessenger"));
        postArrayList.add(new SearchCountryPojo("BaptistMinister"));
        postArrayList.add(new SearchCountryPojo("BarManager"));
        postArrayList.add(new SearchCountryPojo("BarSteward"));
        postArrayList.add(new SearchCountryPojo("Barber"));
        postArrayList.add(new SearchCountryPojo("Barmaid"));
        postArrayList.add(new SearchCountryPojo("Barman"));
        postArrayList.add(new SearchCountryPojo("Barrister"));
        postArrayList.add(new SearchCountryPojo("Beautician"));
        postArrayList.add(new SearchCountryPojo("BeautyTherapist"));
        postArrayList.add(new SearchCountryPojo("BettingShop"));
        postArrayList.add(new SearchCountryPojo("BillPoster"));
        postArrayList.add(new SearchCountryPojo("BingoCaller"));
        postArrayList.add(new SearchCountryPojo("Biochemist"));
        postArrayList.add(new SearchCountryPojo("Biologist"));
        postArrayList.add(new SearchCountryPojo("Blacksmith"));
        postArrayList.add(new SearchCountryPojo("BlindAssembler"));
        postArrayList.add(new SearchCountryPojo("BlindFitter"));
        postArrayList.add(new SearchCountryPojo("BlindsInstaller"));
        postArrayList.add(new SearchCountryPojo("BoatBuilder"));
        postArrayList.add(new SearchCountryPojo("BodyFitter"));
        postArrayList.add(new SearchCountryPojo("Bodyguard"));
        postArrayList.add(new SearchCountryPojo("Bodyshop"));
        postArrayList.add(new SearchCountryPojo("BookBinder"));
        postArrayList.add(new SearchCountryPojo("BookSeller"));
        postArrayList.add(new SearchCountryPojo("Book-Keeper"));
        postArrayList.add(new SearchCountryPojo("BookingAgent"));
        postArrayList.add(new SearchCountryPojo("BookingClerk"));
        postArrayList.add(new SearchCountryPojo("Bookmaker"));
        postArrayList.add(new SearchCountryPojo("Botanist"));
        postArrayList.add(new SearchCountryPojo("BranchManager"));
        postArrayList.add(new SearchCountryPojo("Breeder"));
        postArrayList.add(new SearchCountryPojo("Brewer"));
        postArrayList.add(new SearchCountryPojo("BreweryManager"));
        postArrayList.add(new SearchCountryPojo("BreweryWorker"));
        postArrayList.add(new SearchCountryPojo("Bricklayer"));
        postArrayList.add(new SearchCountryPojo("Broadcaster"));
        postArrayList.add(new SearchCountryPojo("Builder"));
        postArrayList.add(new SearchCountryPojo("BuildersLabourer"));
        postArrayList.add(new SearchCountryPojo("BuildingAdvisor"));
        postArrayList.add(new SearchCountryPojo("BuildingControl"));
        postArrayList.add(new SearchCountryPojo("BuildingEngineer"));
        postArrayList.add(new SearchCountryPojo("BuildingEstimator"));
        postArrayList.add(new SearchCountryPojo("BuildingForeman"));
        postArrayList.add(new SearchCountryPojo("BuildingInspector"));
        postArrayList.add(new SearchCountryPojo("BuildingManager"));
        postArrayList.add(new SearchCountryPojo("BuildingSurveyor"));
        postArrayList.add(new SearchCountryPojo("Bursar"));
        postArrayList.add(new SearchCountryPojo("BusCompany"));
        postArrayList.add(new SearchCountryPojo("BusConductor"));
        postArrayList.add(new SearchCountryPojo("BusDriver"));
        postArrayList.add(new SearchCountryPojo("BusMechanic"));
        postArrayList.add(new SearchCountryPojo("BusValeter"));
        postArrayList.add(new SearchCountryPojo("BusinessConsultant"));
        postArrayList.add(new SearchCountryPojo("BusinessProprietor"));
        postArrayList.add(new SearchCountryPojo("Butcher"));
        postArrayList.add(new SearchCountryPojo("ButcheryManager"));
        postArrayList.add(new SearchCountryPojo("Butler"));
        postArrayList.add(new SearchCountryPojo("Buyer"));
        postArrayList.add(new SearchCountryPojo("CabDriver"));
        postArrayList.add(new SearchCountryPojo("CabinetMaker"));
        postArrayList.add(new SearchCountryPojo("CableContractor"));
        postArrayList.add(new SearchCountryPojo("CableJointer"));
        postArrayList.add(new SearchCountryPojo("CableTVInstaller"));
        postArrayList.add(new SearchCountryPojo("CafeOwner"));
        postArrayList.add(new SearchCountryPojo("CafeStaff"));
        postArrayList.add(new SearchCountryPojo("CafeWorker"));
        postArrayList.add(new SearchCountryPojo("CalibrationManager"));
        postArrayList.add(new SearchCountryPojo("CameraRepairer"));
        postArrayList.add(new SearchCountryPojo("Cameraman"));
        postArrayList.add(new SearchCountryPojo("CarDealer"));
        postArrayList.add(new SearchCountryPojo("CarDeliveryDriver"));
        postArrayList.add(new SearchCountryPojo("CarParkAttendant"));
        postArrayList.add(new SearchCountryPojo("CarSalesman"));
        postArrayList.add(new SearchCountryPojo("CarValet"));
        postArrayList.add(new SearchCountryPojo("CarWashAttendant"));
        postArrayList.add(new SearchCountryPojo("CareAssistant"));
        postArrayList.add(new SearchCountryPojo("CareManager"));
        postArrayList.add(new SearchCountryPojo("CareersAdvisor"));
        postArrayList.add(new SearchCountryPojo("CareersOfficer"));
        postArrayList.add(new SearchCountryPojo("Caretaker"));
        postArrayList.add(new SearchCountryPojo("CargoOperator"));
        postArrayList.add(new SearchCountryPojo("Carpenter"));
        postArrayList.add(new SearchCountryPojo("CarpetCleaner"));
        postArrayList.add(new SearchCountryPojo("CarpetFitter"));
        postArrayList.add(new SearchCountryPojo("CarpetRetailer"));
        postArrayList.add(new SearchCountryPojo("CarphoneFitter"));
        postArrayList.add(new SearchCountryPojo("Cartographer"));
        postArrayList.add(new SearchCountryPojo("Cartoonist"));
        postArrayList.add(new SearchCountryPojo("Cashier"));
        postArrayList.add(new SearchCountryPojo("CasualWorker"));
        postArrayList.add(new SearchCountryPojo("Caterer"));
        postArrayList.add(new SearchCountryPojo("CateringConsultant"));
        postArrayList.add(new SearchCountryPojo("CateringManager"));
        postArrayList.add(new SearchCountryPojo("CateringStaff"));
        postArrayList.add(new SearchCountryPojo("Caulker"));
        postArrayList.add(new SearchCountryPojo("CeilingContractor"));
        postArrayList.add(new SearchCountryPojo("CeilingFixer"));
        postArrayList.add(new SearchCountryPojo("Cellarman"));
        postArrayList.add(new SearchCountryPojo("Chambermaid"));
        postArrayList.add(new SearchCountryPojo("Chandler"));
        postArrayList.add(new SearchCountryPojo("Chaplain"));
        postArrayList.add(new SearchCountryPojo("ChargeHand"));
        postArrayList.add(new SearchCountryPojo("CharityWorker"));
        postArrayList.add(new SearchCountryPojo("Chartered"));
        postArrayList.add(new SearchCountryPojo("CharteredAccountant"));
        postArrayList.add(new SearchCountryPojo("Chauffeur"));
        postArrayList.add(new SearchCountryPojo("Chef"));
        postArrayList.add(new SearchCountryPojo("Chemist"));
        postArrayList.add(new SearchCountryPojo("ChickenChaser"));
        postArrayList.add(new SearchCountryPojo("ChildMinder"));
        postArrayList.add(new SearchCountryPojo("Childminder"));
        postArrayList.add(new SearchCountryPojo("ChimneySweep"));
        postArrayList.add(new SearchCountryPojo("ChinaRestorer"));
        postArrayList.add(new SearchCountryPojo("Chiropodist"));
        postArrayList.add(new SearchCountryPojo("Chiropractor"));
        postArrayList.add(new SearchCountryPojo("Choreographer"));
        postArrayList.add(new SearchCountryPojo("ChurchOfficer"));
        postArrayList.add(new SearchCountryPojo("ChurchWarden"));
        postArrayList.add(new SearchCountryPojo("CinemaManager"));
        postArrayList.add(new SearchCountryPojo("CircusProprietor"));
        postArrayList.add(new SearchCountryPojo("CircusWorker"));
        postArrayList.add(new SearchCountryPojo("CivilEngineer"));
        postArrayList.add(new SearchCountryPojo("CivilServant"));
        postArrayList.add(new SearchCountryPojo("ClaimsAdjustor"));
        postArrayList.add(new SearchCountryPojo("ClaimsAssessor"));
        postArrayList.add(new SearchCountryPojo("ClaimsManager"));
        postArrayList.add(new SearchCountryPojo("Clairvoyant"));
        postArrayList.add(new SearchCountryPojo("ClassroomAide"));
        postArrayList.add(new SearchCountryPojo("Cleaner"));
        postArrayList.add(new SearchCountryPojo("Clergyman"));
        postArrayList.add(new SearchCountryPojo("Cleric"));
        postArrayList.add(new SearchCountryPojo("Clerk"));
        postArrayList.add(new SearchCountryPojo("Commissioned"));
        postArrayList.add(new SearchCountryPojo("Consultant"));
        postArrayList.add(new SearchCountryPojo("Coroner"));
        postArrayList.add(new SearchCountryPojo("Councillor"));
        postArrayList.add(new SearchCountryPojo("Counsellor"));
        postArrayList.add(new SearchCountryPojo("Dealer"));
        postArrayList.add(new SearchCountryPojo("Decorator"));
        postArrayList.add(new SearchCountryPojo("DeliveryDriver"));
        postArrayList.add(new SearchCountryPojo("Doctor"));
        postArrayList.add(new SearchCountryPojo("Driver"));
        postArrayList.add(new SearchCountryPojo("Economist"));
        postArrayList.add(new SearchCountryPojo("Editor"));
        postArrayList.add(new SearchCountryPojo("Employee"));
        postArrayList.add(new SearchCountryPojo("Employment"));
        postArrayList.add(new SearchCountryPojo("Engineer"));
        postArrayList.add(new SearchCountryPojo("EnglishTeacher"));
        postArrayList.add(new SearchCountryPojo("Entertainer"));
        postArrayList.add(new SearchCountryPojo("Envoy"));
        postArrayList.add(new SearchCountryPojo("Executive"));
        postArrayList.add(new SearchCountryPojo("Farmer"));
        postArrayList.add(new SearchCountryPojo("Fireman"));
        postArrayList.add(new SearchCountryPojo("FloorLayer"));
        postArrayList.add(new SearchCountryPojo("FloorManager"));
        postArrayList.add(new SearchCountryPojo("Florist"));
        postArrayList.add(new SearchCountryPojo("FlourMiller"));
        postArrayList.add(new SearchCountryPojo("FlowerArranger"));
        postArrayList.add(new SearchCountryPojo("FlyingInstructor"));
        postArrayList.add(new SearchCountryPojo("FoamConvertor"));
        postArrayList.add(new SearchCountryPojo("FoodProcessor"));
        postArrayList.add(new SearchCountryPojo("Footballer"));
        postArrayList.add(new SearchCountryPojo("Foreman"));
        postArrayList.add(new SearchCountryPojo("ForensicScientist"));
        postArrayList.add(new SearchCountryPojo("ForestRanger"));
        postArrayList.add(new SearchCountryPojo("Forester"));
        postArrayList.add(new SearchCountryPojo("ForkLiftTruckDriver"));
        postArrayList.add(new SearchCountryPojo("ForwardingAgent"));
        postArrayList.add(new SearchCountryPojo("FosterParent"));
        postArrayList.add(new SearchCountryPojo("FoundryWorker"));
        postArrayList.add(new SearchCountryPojo("FraudInvestigator"));
        postArrayList.add(new SearchCountryPojo("FrenchPolisher"));
        postArrayList.add(new SearchCountryPojo("Fruiterer"));
        postArrayList.add(new SearchCountryPojo("FuelMerchant"));
        postArrayList.add(new SearchCountryPojo("FundRaiser"));
        postArrayList.add(new SearchCountryPojo("FuneralDirector"));
        postArrayList.add(new SearchCountryPojo("FuneralFurnisher"));
        postArrayList.add(new SearchCountryPojo("FurnaceMan"));
        postArrayList.add(new SearchCountryPojo("FurnitureDealer"));
        postArrayList.add(new SearchCountryPojo("FurnitureRemover"));
        postArrayList.add(new SearchCountryPojo("FurnitureRestorer"));
        postArrayList.add(new SearchCountryPojo("Furrier"));
        postArrayList.add(new SearchCountryPojo("GalleryOwner"));
        postArrayList.add(new SearchCountryPojo("Gambler"));
        postArrayList.add(new SearchCountryPojo("Gamekeeper"));
        postArrayList.add(new SearchCountryPojo("GamingBoardInspector"));
        postArrayList.add(new SearchCountryPojo("GamingClubManager"));
        postArrayList.add(new SearchCountryPojo("GamingClubProprietor"));
        postArrayList.add(new SearchCountryPojo("GarageAttendant"));
        postArrayList.add(new SearchCountryPojo("GarageForeman"));
        postArrayList.add(new SearchCountryPojo("GarageManager"));
        postArrayList.add(new SearchCountryPojo("Garda"));
        postArrayList.add(new SearchCountryPojo("GardenDesigner"));
        postArrayList.add(new SearchCountryPojo("Gardener"));
        postArrayList.add(new SearchCountryPojo("GasFitter"));
        postArrayList.add(new SearchCountryPojo("GasMechanic"));
        postArrayList.add(new SearchCountryPojo("GasTechnician"));
        postArrayList.add(new SearchCountryPojo("GateKeeper"));
        postArrayList.add(new SearchCountryPojo("Genealogist"));
        postArrayList.add(new SearchCountryPojo("GeneralPractitioner"));
        postArrayList.add(new SearchCountryPojo("Geologist"));
        postArrayList.add(new SearchCountryPojo("Geophysicist"));
        postArrayList.add(new SearchCountryPojo("Gilder"));
        postArrayList.add(new SearchCountryPojo("GlassWorker"));
        postArrayList.add(new SearchCountryPojo("Glazier"));
        postArrayList.add(new SearchCountryPojo("Goldsmith"));
        postArrayList.add(new SearchCountryPojo("GolfCaddy"));
        postArrayList.add(new SearchCountryPojo("GolfClubProfessional"));
        postArrayList.add(new SearchCountryPojo("Golfer"));
        postArrayList.add(new SearchCountryPojo("GoodsHandler"));
        postArrayList.add(new SearchCountryPojo("Governor"));
        postArrayList.add(new SearchCountryPojo("GraniteTechnician"));
        postArrayList.add(new SearchCountryPojo("GraphicDesigner"));
        postArrayList.add(new SearchCountryPojo("Graphologist"));
        postArrayList.add(new SearchCountryPojo("GraveDigger"));
        postArrayList.add(new SearchCountryPojo("GravelMerchant"));
        postArrayList.add(new SearchCountryPojo("GreenKeeper"));
        postArrayList.add(new SearchCountryPojo("Greengrocer"));
        postArrayList.add(new SearchCountryPojo("Grocer"));
        postArrayList.add(new SearchCountryPojo("Groom"));
        postArrayList.add(new SearchCountryPojo("GroundWorker"));
        postArrayList.add(new SearchCountryPojo("Groundsman"));
        postArrayList.add(new SearchCountryPojo("GuestHouseOwner"));
        postArrayList.add(new SearchCountryPojo("GuestHouseProprietor"));
        postArrayList.add(new SearchCountryPojo("GunSmith"));
        postArrayList.add(new SearchCountryPojo("Gynaecologist"));
        postArrayList.add(new SearchCountryPojo("HGVDriver"));
        postArrayList.add(new SearchCountryPojo("HGVMechanic"));
        postArrayList.add(new SearchCountryPojo("Hairdresser"));
        postArrayList.add(new SearchCountryPojo("Handyman"));
        postArrayList.add(new SearchCountryPojo("HardwareDealer"));
        postArrayList.add(new SearchCountryPojo("HaulageContractor"));
        postArrayList.add(new SearchCountryPojo("Hawker"));
        postArrayList.add(new SearchCountryPojo("HealthAdvisor"));
        postArrayList.add(new SearchCountryPojo("HealthAndSafety"));
        postArrayList.add(new SearchCountryPojo("HealthCareAssistant"));
        postArrayList.add(new SearchCountryPojo("HealthConsultant"));
        postArrayList.add(new SearchCountryPojo("HealthNurse"));
        postArrayList.add(new SearchCountryPojo("HealthPlanner"));
        postArrayList.add(new SearchCountryPojo("HealthService"));
        postArrayList.add(new SearchCountryPojo("HealthTherapist"));
        postArrayList.add(new SearchCountryPojo("HealthVisitor"));
        postArrayList.add(new SearchCountryPojo("HearingTherapist"));
        postArrayList.add(new SearchCountryPojo("HeatingEngineer"));
        postArrayList.add(new SearchCountryPojo("Herbalist"));
        postArrayList.add(new SearchCountryPojo("HighwayInspector"));
        postArrayList.add(new SearchCountryPojo("HireCarDriver"));
        postArrayList.add(new SearchCountryPojo("Historian"));
        postArrayList.add(new SearchCountryPojo("HistoryTeacher"));
        postArrayList.add(new SearchCountryPojo("HodCarrier"));
        postArrayList.add(new SearchCountryPojo("HomeEconomist"));
        postArrayList.add(new SearchCountryPojo("HomeHelp"));
        postArrayList.add(new SearchCountryPojo("HomecareManager"));
        postArrayList.add(new SearchCountryPojo("Homeopath"));
        postArrayList.add(new SearchCountryPojo("Homeworker"));
        postArrayList.add(new SearchCountryPojo("HopMerchant"));
        postArrayList.add(new SearchCountryPojo("HorseBreeder"));
        postArrayList.add(new SearchCountryPojo("HorseDealer"));
        postArrayList.add(new SearchCountryPojo("HorseRidingInstructor"));
        postArrayList.add(new SearchCountryPojo("HorseTrader"));
        postArrayList.add(new SearchCountryPojo("HorseTrainer"));
        postArrayList.add(new SearchCountryPojo("HorticulturalConsultant"));
        postArrayList.add(new SearchCountryPojo("Horticulturalist"));
        postArrayList.add(new SearchCountryPojo("HosieryMechanic"));
        postArrayList.add(new SearchCountryPojo("HosieryWorker"));
        postArrayList.add(new SearchCountryPojo("HospitalConsultant"));
        postArrayList.add(new SearchCountryPojo("HospitalDoctor"));
        postArrayList.add(new SearchCountryPojo("HospitalManager"));
        postArrayList.add(new SearchCountryPojo("HospitalOrderly"));
        postArrayList.add(new SearchCountryPojo("HospitalTechnician"));
        postArrayList.add(new SearchCountryPojo("HospitalWarden"));
        postArrayList.add(new SearchCountryPojo("HospitalWorker"));
        postArrayList.add(new SearchCountryPojo("Hostess"));
        postArrayList.add(new SearchCountryPojo("HotFoilPrinter"));
        postArrayList.add(new SearchCountryPojo("HotelConsultant"));
        postArrayList.add(new SearchCountryPojo("HotelWorker"));
        postArrayList.add(new SearchCountryPojo("Hotelier"));
        postArrayList.add(new SearchCountryPojo("Househusband"));
        postArrayList.add(new SearchCountryPojo("Housekeeper"));
        postArrayList.add(new SearchCountryPojo("Housewife"));
        postArrayList.add(new SearchCountryPojo("HousingAssistant"));
        postArrayList.add(new SearchCountryPojo("HousingOfficer"));
        postArrayList.add(new SearchCountryPojo("HousingSupervisor"));
        postArrayList.add(new SearchCountryPojo("Hygienist"));
        postArrayList.add(new SearchCountryPojo("Hypnotherapist"));
        postArrayList.add(new SearchCountryPojo("Hypnotist"));
        postArrayList.add(new SearchCountryPojo("ITConsultant"));
        postArrayList.add(new SearchCountryPojo("ITManager"));
        postArrayList.add(new SearchCountryPojo("ITTrainer"));
        postArrayList.add(new SearchCountryPojo("IceCreamVendor"));
        postArrayList.add(new SearchCountryPojo("Illustrator"));
        postArrayList.add(new SearchCountryPojo("ImmigrationOfficer"));
        postArrayList.add(new SearchCountryPojo("ImportConsultant"));
        postArrayList.add(new SearchCountryPojo("Importer"));
        postArrayList.add(new SearchCountryPojo("IndependentMeans"));
        postArrayList.add(new SearchCountryPojo("InductionMoulder"));
        postArrayList.add(new SearchCountryPojo("IndustrialChemist"));
        postArrayList.add(new SearchCountryPojo("IndustrialConsultant"));
        postArrayList.add(new SearchCountryPojo("InjectionMoulder"));
        postArrayList.add(new SearchCountryPojo("Inspector"));
        postArrayList.add(new SearchCountryPojo("Instructor"));
        postArrayList.add(new SearchCountryPojo("InstrumentEngineer"));
        postArrayList.add(new SearchCountryPojo("InstrumentMaker"));
        postArrayList.add(new SearchCountryPojo("InstrumentSupervisor"));
        postArrayList.add(new SearchCountryPojo("InstrumentTechnician"));
        postArrayList.add(new SearchCountryPojo("InsuranceAgent"));
        postArrayList.add(new SearchCountryPojo("InsuranceAssessor"));
        postArrayList.add(new SearchCountryPojo("InsuranceBroker"));
        postArrayList.add(new SearchCountryPojo("InsuranceConsultant"));
        postArrayList.add(new SearchCountryPojo("InsuranceInspector"));
        postArrayList.add(new SearchCountryPojo("InsuranceStaff"));
        postArrayList.add(new SearchCountryPojo("InteriorDecorator"));
        postArrayList.add(new SearchCountryPojo("InteriorDesigner"));
        postArrayList.add(new SearchCountryPojo("Interpreter"));
        postArrayList.add(new SearchCountryPojo("Interviewer"));
        postArrayList.add(new SearchCountryPojo("Inventor"));
        postArrayList.add(new SearchCountryPojo("Investigator"));
        postArrayList.add(new SearchCountryPojo("InvestmentAdvisor"));
        postArrayList.add(new SearchCountryPojo("InvestmentBanker"));
        postArrayList.add(new SearchCountryPojo("InvestmentManager"));
        postArrayList.add(new SearchCountryPojo("InvestmentStrategist"));
        postArrayList.add(new SearchCountryPojo("Ironmonger"));
        postArrayList.add(new SearchCountryPojo("Janitor"));
        postArrayList.add(new SearchCountryPojo("JazzComposer"));
        postArrayList.add(new SearchCountryPojo("Jeweller"));
        postArrayList.add(new SearchCountryPojo("Jewellery"));
        postArrayList.add(new SearchCountryPojo("Jockey"));
        postArrayList.add(new SearchCountryPojo("Joiner"));
        postArrayList.add(new SearchCountryPojo("JoineryConsultant"));
        postArrayList.add(new SearchCountryPojo("Journalist"));
        postArrayList.add(new SearchCountryPojo("Judge"));
        postArrayList.add(new SearchCountryPojo("KeepFitInstructor"));
        postArrayList.add(new SearchCountryPojo("KennelHand"));
        postArrayList.add(new SearchCountryPojo("KitchenWorker"));
        postArrayList.add(new SearchCountryPojo("Knitter"));
        postArrayList.add(new SearchCountryPojo("LabellingOperator"));
        postArrayList.add(new SearchCountryPojo("LaboratoryAnalyst"));
        postArrayList.add(new SearchCountryPojo("Labourer"));
        postArrayList.add(new SearchCountryPojo("Laminator"));
        postArrayList.add(new SearchCountryPojo("LampshadeMaker"));
        postArrayList.add(new SearchCountryPojo("LandAgent"));
        postArrayList.add(new SearchCountryPojo("LandSurveyor"));
        postArrayList.add(new SearchCountryPojo("Landlady"));
        postArrayList.add(new SearchCountryPojo("Landlord"));
        postArrayList.add(new SearchCountryPojo("Landowner"));
        postArrayList.add(new SearchCountryPojo("Landworker"));
        postArrayList.add(new SearchCountryPojo("LatheOperator"));
        postArrayList.add(new SearchCountryPojo("LaundryStaff"));
        postArrayList.add(new SearchCountryPojo("LaundryWorker"));
        postArrayList.add(new SearchCountryPojo("LavatoryAttendant"));
        postArrayList.add(new SearchCountryPojo("LawClerk"));
        postArrayList.add(new SearchCountryPojo("LawnMower"));
        postArrayList.add(new SearchCountryPojo("Lawyer"));
        postArrayList.add(new SearchCountryPojo("LeafletDistributor"));
        postArrayList.add(new SearchCountryPojo("LeatherWorker"));
        postArrayList.add(new SearchCountryPojo("Lecturer"));
        postArrayList.add(new SearchCountryPojo("LedgerClerk"));
        postArrayList.add(new SearchCountryPojo("LegalAdvisor"));
        postArrayList.add(new SearchCountryPojo("LegalAssistant"));
        postArrayList.add(new SearchCountryPojo("LegalExecutive"));
        postArrayList.add(new SearchCountryPojo("LegalSecretary"));
        postArrayList.add(new SearchCountryPojo("LettingAgent"));
        postArrayList.add(new SearchCountryPojo("LiaisonOfficer"));
        postArrayList.add(new SearchCountryPojo("Librarian"));
        postArrayList.add(new SearchCountryPojo("LibraryManager"));
        postArrayList.add(new SearchCountryPojo("LicensedPremises"));
        postArrayList.add(new SearchCountryPojo("Licensee"));
        postArrayList.add(new SearchCountryPojo("Licensing"));
        postArrayList.add(new SearchCountryPojo("Lifeguard"));
        postArrayList.add(new SearchCountryPojo("LiftAttendant"));
        postArrayList.add(new SearchCountryPojo("LiftEngineer"));
        postArrayList.add(new SearchCountryPojo("Lighterman"));
        postArrayList.add(new SearchCountryPojo("LighthouseKeeper"));
        postArrayList.add(new SearchCountryPojo("LightingDesigner"));
        postArrayList.add(new SearchCountryPojo("LightingTechnician"));
        postArrayList.add(new SearchCountryPojo("LimeKilnAttendant"));
        postArrayList.add(new SearchCountryPojo("LineManager"));
        postArrayList.add(new SearchCountryPojo("LineWorker"));
        postArrayList.add(new SearchCountryPojo("Lineman"));
        postArrayList.add(new SearchCountryPojo("Linguist"));
        postArrayList.add(new SearchCountryPojo("LiteraryAgent"));
        postArrayList.add(new SearchCountryPojo("LiteraryEditor"));
        postArrayList.add(new SearchCountryPojo("Lithographer"));
        postArrayList.add(new SearchCountryPojo("LitigationManager"));
        postArrayList.add(new SearchCountryPojo("LoansManager"));
        postArrayList.add(new SearchCountryPojo("LocalGovernment"));
        postArrayList.add(new SearchCountryPojo("LockKeeper"));
        postArrayList.add(new SearchCountryPojo("Locksmith"));
        postArrayList.add(new SearchCountryPojo("LocumPharmacist"));
        postArrayList.add(new SearchCountryPojo("LogMerchant"));
        postArrayList.add(new SearchCountryPojo("LorryDriver"));
        postArrayList.add(new SearchCountryPojo("LossAdjustor"));
        postArrayList.add(new SearchCountryPojo("LossAssessor"));
        postArrayList.add(new SearchCountryPojo("Lumberjack"));
        postArrayList.add(new SearchCountryPojo("MachineFitters"));
        postArrayList.add(new SearchCountryPojo("MachineMinder"));
        postArrayList.add(new SearchCountryPojo("MachineOperator"));
        postArrayList.add(new SearchCountryPojo("MachineSetter"));
        postArrayList.add(new SearchCountryPojo("MachineTool"));
        postArrayList.add(new SearchCountryPojo("MachineToolFitter"));
        postArrayList.add(new SearchCountryPojo("Machinist"));
        postArrayList.add(new SearchCountryPojo("Magician"));
        postArrayList.add(new SearchCountryPojo("Magistrate"));
        postArrayList.add(new SearchCountryPojo("MagistratesClerk"));
        postArrayList.add(new SearchCountryPojo("Maid"));
        postArrayList.add(new SearchCountryPojo("MaintenanceFitter"));
        postArrayList.add(new SearchCountryPojo("MakeUpArtist"));
        postArrayList.add(new SearchCountryPojo("Manicurist"));
        postArrayList.add(new SearchCountryPojo("Manufacturing"));
        postArrayList.add(new SearchCountryPojo("MapMounter"));
        postArrayList.add(new SearchCountryPojo("MarbleFinisher"));
        postArrayList.add(new SearchCountryPojo("MarbleMason"));
        postArrayList.add(new SearchCountryPojo("MarineBroker"));
        postArrayList.add(new SearchCountryPojo("MarineConsultant"));
        postArrayList.add(new SearchCountryPojo("MarineElectrician"));
        postArrayList.add(new SearchCountryPojo("MarineEngineer"));
        postArrayList.add(new SearchCountryPojo("MarineGeologist"));
        postArrayList.add(new SearchCountryPojo("MarinePilot"));
        postArrayList.add(new SearchCountryPojo("MarineSurveyor"));
        postArrayList.add(new SearchCountryPojo("MarketGardener"));
        postArrayList.add(new SearchCountryPojo("MarketResearch"));
        postArrayList.add(new SearchCountryPojo("MarketResearcher"));
        postArrayList.add(new SearchCountryPojo("MarketTrader"));
        postArrayList.add(new SearchCountryPojo("MarketingAgent"));
        postArrayList.add(new SearchCountryPojo("MarketingAssistant"));
        postArrayList.add(new SearchCountryPojo("MarketingCoordinator"));
        postArrayList.add(new SearchCountryPojo("MarketingDirector"));
        postArrayList.add(new SearchCountryPojo("MarketingManager"));
        postArrayList.add(new SearchCountryPojo("MarqueeErector"));
        postArrayList.add(new SearchCountryPojo("MassageTherapist"));
        postArrayList.add(new SearchCountryPojo("Masseur"));
        postArrayList.add(new SearchCountryPojo("Masseuse"));
        postArrayList.add(new SearchCountryPojo("MasterMariner"));
        postArrayList.add(new SearchCountryPojo("MaterialsController"));
        postArrayList.add(new SearchCountryPojo("MaterialsManager"));
        postArrayList.add(new SearchCountryPojo("Mathematician"));
        postArrayList.add(new SearchCountryPojo("MathsTeacher"));
        postArrayList.add(new SearchCountryPojo("Matron"));
        postArrayList.add(new SearchCountryPojo("MattressMaker"));
        postArrayList.add(new SearchCountryPojo("MeatInspector"));
        postArrayList.add(new SearchCountryPojo("MeatWholesaler"));
        postArrayList.add(new SearchCountryPojo("Mechanic"));
        postArrayList.add(new SearchCountryPojo("MedalDealer"));
        postArrayList.add(new SearchCountryPojo("MedicalAdvisor"));
        postArrayList.add(new SearchCountryPojo("MedicalAssistant"));
        postArrayList.add(new SearchCountryPojo("MedicalConsultant"));
        postArrayList.add(new SearchCountryPojo("MedicalOfficer"));
        postArrayList.add(new SearchCountryPojo("MedicalPhysicist"));
        postArrayList.add(new SearchCountryPojo("MedicalPractitioner"));
        postArrayList.add(new SearchCountryPojo("MedicalResearcher"));
        postArrayList.add(new SearchCountryPojo("MedicalSecretary"));
        postArrayList.add(new SearchCountryPojo("MedicalStudent"));
        postArrayList.add(new SearchCountryPojo("MedicalSupplier"));
        postArrayList.add(new SearchCountryPojo("MedicalTechnician"));
        postArrayList.add(new SearchCountryPojo("Merchandiser"));
        postArrayList.add(new SearchCountryPojo("Merchant"));
        postArrayList.add(new SearchCountryPojo("MerchantBanker"));
        postArrayList.add(new SearchCountryPojo("MerchantSeaman"));
        postArrayList.add(new SearchCountryPojo("Messenger"));
        postArrayList.add(new SearchCountryPojo("MetalDealer"));
        postArrayList.add(new SearchCountryPojo("MetalEngineer"));
        postArrayList.add(new SearchCountryPojo("MetalPolisher"));
        postArrayList.add(new SearchCountryPojo("MetalWorker"));
        postArrayList.add(new SearchCountryPojo("Metallurgist"));
        postArrayList.add(new SearchCountryPojo("Meteorologist"));
        postArrayList.add(new SearchCountryPojo("MeterReader"));
        postArrayList.add(new SearchCountryPojo("Microbiologist"));
        postArrayList.add(new SearchCountryPojo("Midwife"));
        postArrayList.add(new SearchCountryPojo("MilitaryLeader"));
        postArrayList.add(new SearchCountryPojo("Milklady"));
        postArrayList.add(new SearchCountryPojo("Milkman"));
        postArrayList.add(new SearchCountryPojo("MillOperator"));
        postArrayList.add(new SearchCountryPojo("MillWorker"));
        postArrayList.add(new SearchCountryPojo("Miller"));
        postArrayList.add(new SearchCountryPojo("Milliner"));
        postArrayList.add(new SearchCountryPojo("Millwright"));
        postArrayList.add(new SearchCountryPojo("Miner"));
        postArrayList.add(new SearchCountryPojo("Mineralologist"));
        postArrayList.add(new SearchCountryPojo("MinibusDriver"));
        postArrayList.add(new SearchCountryPojo("MinicabDriver"));
        postArrayList.add(new SearchCountryPojo("MiningConsultant"));
        postArrayList.add(new SearchCountryPojo("MiningEngineer"));
        postArrayList.add(new SearchCountryPojo("MoneyBroker"));
        postArrayList.add(new SearchCountryPojo("Moneylender"));
        postArrayList.add(new SearchCountryPojo("MooringContractor"));
        postArrayList.add(new SearchCountryPojo("MortgageBroker"));
        postArrayList.add(new SearchCountryPojo("Mortician"));
        postArrayList.add(new SearchCountryPojo("MotorDealer"));
        postArrayList.add(new SearchCountryPojo("MotorEngineer"));
        postArrayList.add(new SearchCountryPojo("MotorFitter"));
        postArrayList.add(new SearchCountryPojo("MotorMechanic"));
        postArrayList.add(new SearchCountryPojo("MotorRacing"));
        postArrayList.add(new SearchCountryPojo("MotorTrader"));
        postArrayList.add(new SearchCountryPojo("MuseumAssistant"));
        postArrayList.add(new SearchCountryPojo("MuseumAttendant"));
        postArrayList.add(new SearchCountryPojo("MusicTeacher"));
        postArrayList.add(new SearchCountryPojo("Musician"));
        postArrayList.add(new SearchCountryPojo("Nanny"));
        postArrayList.add(new SearchCountryPojo("Navigator"));
        postArrayList.add(new SearchCountryPojo("Negotiator"));
        postArrayList.add(new SearchCountryPojo("Neurologist"));
        postArrayList.add(new SearchCountryPojo("Newsagent"));
        postArrayList.add(new SearchCountryPojo("NightPorter"));
        postArrayList.add(new SearchCountryPojo("NightWatchman"));
        postArrayList.add(new SearchCountryPojo("NuclearScientist"));
        postArrayList.add(new SearchCountryPojo("Nun"));
        postArrayList.add(new SearchCountryPojo("Nurse"));
        postArrayList.add(new SearchCountryPojo("NurseryAssistant"));
        postArrayList.add(new SearchCountryPojo("NurseryNurse"));
        postArrayList.add(new SearchCountryPojo("NurseryWorker"));
        postArrayList.add(new SearchCountryPojo("Nurseryman"));
        postArrayList.add(new SearchCountryPojo("NursingAssistant"));
        postArrayList.add(new SearchCountryPojo("NursingAuxiliary"));
        postArrayList.add(new SearchCountryPojo("NursingManager"));
        postArrayList.add(new SearchCountryPojo("NursingSister"));
        postArrayList.add(new SearchCountryPojo("Nutritionist"));
        postArrayList.add(new SearchCountryPojo("OffShore"));
        postArrayList.add(new SearchCountryPojo("OfficeManager"));
        postArrayList.add(new SearchCountryPojo("OfficeWorker"));
        postArrayList.add(new SearchCountryPojo("OilBroker"));
        postArrayList.add(new SearchCountryPojo("OilRigCrew"));
        postArrayList.add(new SearchCountryPojo("OperaSinger"));
        postArrayList.add(new SearchCountryPojo("Operations"));
        postArrayList.add(new SearchCountryPojo("Operative"));
        postArrayList.add(new SearchCountryPojo("Operator"));
        postArrayList.add(new SearchCountryPojo("Optical"));
        postArrayList.add(new SearchCountryPojo("OpticalAdvisor"));
        postArrayList.add(new SearchCountryPojo("OpticalAssistant"));
        postArrayList.add(new SearchCountryPojo("Optician"));
        postArrayList.add(new SearchCountryPojo("Optometrist"));
        postArrayList.add(new SearchCountryPojo("Orchestral"));
        postArrayList.add(new SearchCountryPojo("Organiser"));
        postArrayList.add(new SearchCountryPojo("Organist"));
        postArrayList.add(new SearchCountryPojo("Ornamental"));
        postArrayList.add(new SearchCountryPojo("Ornithologist"));
        postArrayList.add(new SearchCountryPojo("Orthopaedic"));
        postArrayList.add(new SearchCountryPojo("Orthoptist"));
        postArrayList.add(new SearchCountryPojo("Osteopath"));
        postArrayList.add(new SearchCountryPojo("OutdoorPursuits"));
        postArrayList.add(new SearchCountryPojo("OutreachWorker"));
        postArrayList.add(new SearchCountryPojo("Packaging"));
        postArrayList.add(new SearchCountryPojo("Packer"));
        postArrayList.add(new SearchCountryPojo("Paediatrician"));
        postArrayList.add(new SearchCountryPojo("PaintConsultant"));
        postArrayList.add(new SearchCountryPojo("Painter"));
        postArrayList.add(new SearchCountryPojo("Palaeobotanist"));
        postArrayList.add(new SearchCountryPojo("Palaeontologist"));
        postArrayList.add(new SearchCountryPojo("PalletMaker"));
        postArrayList.add(new SearchCountryPojo("PanelBeater"));
        postArrayList.add(new SearchCountryPojo("Paramedic"));
        postArrayList.add(new SearchCountryPojo("ParkAttendant"));
        postArrayList.add(new SearchCountryPojo("ParkKeeper"));
        postArrayList.add(new SearchCountryPojo("ParkRanger"));
        postArrayList.add(new SearchCountryPojo("PartitionErector"));
        postArrayList.add(new SearchCountryPojo("PartsMan"));
        postArrayList.add(new SearchCountryPojo("PartsManager"));
        postArrayList.add(new SearchCountryPojo("PartsSupervisor"));
        postArrayList.add(new SearchCountryPojo("PartyPlanner"));
        postArrayList.add(new SearchCountryPojo("Pasteuriser"));
        postArrayList.add(new SearchCountryPojo("PastryChef"));
        postArrayList.add(new SearchCountryPojo("PatentAgent"));
        postArrayList.add(new SearchCountryPojo("PatentAttorney"));
        postArrayList.add(new SearchCountryPojo("Pathologist"));
        postArrayList.add(new SearchCountryPojo("Patrolman"));
        postArrayList.add(new SearchCountryPojo("PatternCutter"));
        postArrayList.add(new SearchCountryPojo("PatternMaker"));
        postArrayList.add(new SearchCountryPojo("PatternWeaver"));
        postArrayList.add(new SearchCountryPojo("Pawnbroker"));
        postArrayList.add(new SearchCountryPojo("PayrollAssistant"));
        postArrayList.add(new SearchCountryPojo("PayrollClerk"));
        postArrayList.add(new SearchCountryPojo("PayrollManager"));
        postArrayList.add(new SearchCountryPojo("PayrollSupervisor"));
        postArrayList.add(new SearchCountryPojo("PersonnelOfficer"));
        postArrayList.add(new SearchCountryPojo("PestController"));
        postArrayList.add(new SearchCountryPojo("PetMinder"));
        postArrayList.add(new SearchCountryPojo("Pharmacist"));
        postArrayList.add(new SearchCountryPojo("Philatelist"));
        postArrayList.add(new SearchCountryPojo("Photographer"));
        postArrayList.add(new SearchCountryPojo("Physician"));
        postArrayList.add(new SearchCountryPojo("Physicist"));
        postArrayList.add(new SearchCountryPojo("Physiologist"));
        postArrayList.add(new SearchCountryPojo("Physiotherapist"));
        postArrayList.add(new SearchCountryPojo("PianoTeacher"));
        postArrayList.add(new SearchCountryPojo("PianoTuner"));
        postArrayList.add(new SearchCountryPojo("PictureEditor"));
        postArrayList.add(new SearchCountryPojo("PictureFramer"));
        postArrayList.add(new SearchCountryPojo("PictureReseacher"));
        postArrayList.add(new SearchCountryPojo("PigMan"));
        postArrayList.add(new SearchCountryPojo("PigManager"));
        postArrayList.add(new SearchCountryPojo("Pilot"));
        postArrayList.add(new SearchCountryPojo("PipeFitter"));
        postArrayList.add(new SearchCountryPojo("PipeInspector"));
        postArrayList.add(new SearchCountryPojo("PipeInsulator"));
        postArrayList.add(new SearchCountryPojo("PipeLayer"));
        postArrayList.add(new SearchCountryPojo("PlanningEngineer"));
        postArrayList.add(new SearchCountryPojo("PlanningManager"));
        postArrayList.add(new SearchCountryPojo("PlanningOfficer"));
        postArrayList.add(new SearchCountryPojo("PlanningTechnician"));
        postArrayList.add(new SearchCountryPojo("PlantAttendant"));
        postArrayList.add(new SearchCountryPojo("PlantDriver"));
        postArrayList.add(new SearchCountryPojo("PlantEngineer"));
        postArrayList.add(new SearchCountryPojo("PlantFitter"));
        postArrayList.add(new SearchCountryPojo("PlantManager"));
        postArrayList.add(new SearchCountryPojo("PlantOperator"));
        postArrayList.add(new SearchCountryPojo("Plasterer"));
        postArrayList.add(new SearchCountryPojo("PlasticsConsultant"));
        postArrayList.add(new SearchCountryPojo("PlasticsEngineer"));
        postArrayList.add(new SearchCountryPojo("PlateLayer"));
        postArrayList.add(new SearchCountryPojo("Plater"));
        postArrayList.add(new SearchCountryPojo("PlaygroupAssistant"));
        postArrayList.add(new SearchCountryPojo("PlaygroupLeader"));
        postArrayList.add(new SearchCountryPojo("Plumber"));
        postArrayList.add(new SearchCountryPojo("Podiatrist"));
        postArrayList.add(new SearchCountryPojo("PoliceOfficer"));
        postArrayList.add(new SearchCountryPojo("Polisher"));
        postArrayList.add(new SearchCountryPojo("PoolAttendant"));
        postArrayList.add(new SearchCountryPojo("PoolsCollector"));
        postArrayList.add(new SearchCountryPojo("Porter"));
        postArrayList.add(new SearchCountryPojo("PortfolioManager"));
        postArrayList.add(new SearchCountryPojo("PostSorter"));
        postArrayList.add(new SearchCountryPojo("Postman"));
        postArrayList.add(new SearchCountryPojo("Postmaster"));
        postArrayList.add(new SearchCountryPojo("Postwoman"));
        postArrayList.add(new SearchCountryPojo("Potter"));
        postArrayList.add(new SearchCountryPojo("PracticeManager"));
        postArrayList.add(new SearchCountryPojo("Preacher"));
        postArrayList.add(new SearchCountryPojo("PrecisionEngineer"));
        postArrayList.add(new SearchCountryPojo("Premises"));
        postArrayList.add(new SearchCountryPojo("PremisesSecurity"));
        postArrayList.add(new SearchCountryPojo("PressOfficer"));
        postArrayList.add(new SearchCountryPojo("PressOperator"));
        postArrayList.add(new SearchCountryPojo("PressSetter"));
        postArrayList.add(new SearchCountryPojo("Presser"));
        postArrayList.add(new SearchCountryPojo("Priest"));
        postArrayList.add(new SearchCountryPojo("PrintFinisher"));
        postArrayList.add(new SearchCountryPojo("Printer"));
        postArrayList.add(new SearchCountryPojo("PrisonChaplain"));
        postArrayList.add(new SearchCountryPojo("PrisonOfficer"));
        postArrayList.add(new SearchCountryPojo("PrivateInvestigator"));
        postArrayList.add(new SearchCountryPojo("ProbationOfficer"));
        postArrayList.add(new SearchCountryPojo("ProbationWorker"));
        postArrayList.add(new SearchCountryPojo("ProcuratorFiscal"));
        postArrayList.add(new SearchCountryPojo("ProduceSupervisor"));
        postArrayList.add(new SearchCountryPojo("Producer"));
        postArrayList.add(new SearchCountryPojo("ProductInstaller"));
        postArrayList.add(new SearchCountryPojo("ProductManager"));
        postArrayList.add(new SearchCountryPojo("ProductionEngineer"));
        postArrayList.add(new SearchCountryPojo("ProductionHand"));
        postArrayList.add(new SearchCountryPojo("ProductionManager"));
        postArrayList.add(new SearchCountryPojo("ProductionPlanner"));
        postArrayList.add(new SearchCountryPojo("ProfessionalBoxer"));
        postArrayList.add(new SearchCountryPojo("ProfessionalRacing"));
        postArrayList.add(new SearchCountryPojo("ProfessionalWrestler"));
        postArrayList.add(new SearchCountryPojo("ProgressChaser"));
        postArrayList.add(new SearchCountryPojo("ProgressClerk"));
        postArrayList.add(new SearchCountryPojo("ProjectCo-ordinator"));
        postArrayList.add(new SearchCountryPojo("ProjectEngineer"));
        postArrayList.add(new SearchCountryPojo("ProjectLeader"));
        postArrayList.add(new SearchCountryPojo("ProjectManager"));
        postArrayList.add(new SearchCountryPojo("ProjectWorker"));
        postArrayList.add(new SearchCountryPojo("Projectionist"));
        postArrayList.add(new SearchCountryPojo("Promoter"));
        postArrayList.add(new SearchCountryPojo("ProofReader"));
        postArrayList.add(new SearchCountryPojo("PropertyBuyer"));
        postArrayList.add(new SearchCountryPojo("PropertyDealer"));
        postArrayList.add(new SearchCountryPojo("PropertyDeveloper"));
        postArrayList.add(new SearchCountryPojo("PropertyManager"));
        postArrayList.add(new SearchCountryPojo("PropertyValuer"));
        postArrayList.add(new SearchCountryPojo("Proprietor"));
        postArrayList.add(new SearchCountryPojo("Psychiatrist"));
        postArrayList.add(new SearchCountryPojo("Psychoanalyst"));
        postArrayList.add(new SearchCountryPojo("Psychologist"));
        postArrayList.add(new SearchCountryPojo("Psychotherapist"));
        postArrayList.add(new SearchCountryPojo("PublicHouseManager"));
        postArrayList.add(new SearchCountryPojo("PublicRelationsOf?cer"));
        postArrayList.add(new SearchCountryPojo("Publican"));
        postArrayList.add(new SearchCountryPojo("PublicityManager"));
        postArrayList.add(new SearchCountryPojo("Publisher"));
        postArrayList.add(new SearchCountryPojo("PublishingManager"));
        postArrayList.add(new SearchCountryPojo("PurchaseClerk"));
        postArrayList.add(new SearchCountryPojo("PurchaseLedgerClerk"));
        postArrayList.add(new SearchCountryPojo("PurchasingAssistant"));
        postArrayList.add(new SearchCountryPojo("PurchasingManager"));
        postArrayList.add(new SearchCountryPojo("Purser"));
        postArrayList.add(new SearchCountryPojo("QualityController"));
        postArrayList.add(new SearchCountryPojo("QualityEngineer"));
        postArrayList.add(new SearchCountryPojo("QualityInspector"));
        postArrayList.add(new SearchCountryPojo("QualityManager"));
        postArrayList.add(new SearchCountryPojo("QualityTechnician"));
        postArrayList.add(new SearchCountryPojo("QuantitySurveyor"));
        postArrayList.add(new SearchCountryPojo("QuarryWorker"));
        postArrayList.add(new SearchCountryPojo("RacehorseGroom"));
        postArrayList.add(new SearchCountryPojo("RacingOrganiser"));
        postArrayList.add(new SearchCountryPojo("RadioController"));
        postArrayList.add(new SearchCountryPojo("RadioDirector"));
        postArrayList.add(new SearchCountryPojo("RadioEngineer"));
        postArrayList.add(new SearchCountryPojo("RadioOperator"));
        postArrayList.add(new SearchCountryPojo("RadioPresenter"));
        postArrayList.add(new SearchCountryPojo("RadioProducer"));
        postArrayList.add(new SearchCountryPojo("Radiographer"));
        postArrayList.add(new SearchCountryPojo("Radiologist"));
        postArrayList.add(new SearchCountryPojo("RallyDriver"));
        postArrayList.add(new SearchCountryPojo("Receptionist"));
        postArrayList.add(new SearchCountryPojo("Recorder"));
        postArrayList.add(new SearchCountryPojo("RecordsSupervisor"));
        postArrayList.add(new SearchCountryPojo("RecoveryVehicleCoordinator"));
        postArrayList.add(new SearchCountryPojo("Recreational"));
        postArrayList.add(new SearchCountryPojo("RecruitmentConsultant"));
        postArrayList.add(new SearchCountryPojo("Rector"));
        postArrayList.add(new SearchCountryPojo("Reflexologist"));
        postArrayList.add(new SearchCountryPojo("RefractoryEngineer"));
        postArrayList.add(new SearchCountryPojo("RefrigerationEngineer"));
        postArrayList.add(new SearchCountryPojo("RefuseCollector"));
        postArrayList.add(new SearchCountryPojo("Registrar"));
        postArrayList.add(new SearchCountryPojo("Regulator"));
        postArrayList.add(new SearchCountryPojo("RelocationAgent"));
        postArrayList.add(new SearchCountryPojo("RemedialTherapist"));
        postArrayList.add(new SearchCountryPojo("RentCollector"));
        postArrayList.add(new SearchCountryPojo("RentOffcer"));
        postArrayList.add(new SearchCountryPojo("RepairMan"));
        postArrayList.add(new SearchCountryPojo("Repairer"));
        postArrayList.add(new SearchCountryPojo("Reporter"));
        postArrayList.add(new SearchCountryPojo("Representative"));
        postArrayList.add(new SearchCountryPojo("ReprographicAssistant"));
        postArrayList.add(new SearchCountryPojo("ResearchAnalyst"));
        postArrayList.add(new SearchCountryPojo("ResearchConsultant"));
        postArrayList.add(new SearchCountryPojo("ResearchDirector"));
        postArrayList.add(new SearchCountryPojo("ResearchScientist"));
        postArrayList.add(new SearchCountryPojo("ResearchTechnician"));
        postArrayList.add(new SearchCountryPojo("Researcher"));
        postArrayList.add(new SearchCountryPojo("ResinCaster"));
        postArrayList.add(new SearchCountryPojo("RestaurantManager"));
        postArrayList.add(new SearchCountryPojo("Restaurateur"));
        postArrayList.add(new SearchCountryPojo("Restorer"));
        postArrayList.add(new SearchCountryPojo("Retired"));
        postArrayList.add(new SearchCountryPojo("RevenueClerk"));
        postArrayList.add(new SearchCountryPojo("RevenueOfficer"));
        postArrayList.add(new SearchCountryPojo("RidingInstructor"));
        postArrayList.add(new SearchCountryPojo("RigWorker"));
        postArrayList.add(new SearchCountryPojo("Rigger"));
        postArrayList.add(new SearchCountryPojo("Riveter"));
        postArrayList.add(new SearchCountryPojo("RoadSafetyOfficer"));
        postArrayList.add(new SearchCountryPojo("RoadSweeper"));
        postArrayList.add(new SearchCountryPojo("RoadWorker"));
        postArrayList.add(new SearchCountryPojo("Roadworker"));
        postArrayList.add(new SearchCountryPojo("RoofTiler"));
        postArrayList.add(new SearchCountryPojo("Roofer"));
        postArrayList.add(new SearchCountryPojo("RoseGrower"));
        postArrayList.add(new SearchCountryPojo("RoyalMarine"));
        postArrayList.add(new SearchCountryPojo("RugMaker"));
        postArrayList.add(new SearchCountryPojo("Saddler"));
        postArrayList.add(new SearchCountryPojo("SafetyOfficer"));
        postArrayList.add(new SearchCountryPojo("SailMaker"));
        postArrayList.add(new SearchCountryPojo("SalesAdministrator"));
        postArrayList.add(new SearchCountryPojo("SalesAssistant"));
        postArrayList.add(new SearchCountryPojo("SalesDirector"));
        postArrayList.add(new SearchCountryPojo("SalesEngineer"));
        postArrayList.add(new SearchCountryPojo("SalesExecutive"));
        postArrayList.add(new SearchCountryPojo("SalesManager"));
        postArrayList.add(new SearchCountryPojo("SalesRepresentative"));
        postArrayList.add(new SearchCountryPojo("SalesSupport"));
        postArrayList.add(new SearchCountryPojo("Salesman"));
        postArrayList.add(new SearchCountryPojo("Saleswoman"));
        postArrayList.add(new SearchCountryPojo("SandBlaster"));
        postArrayList.add(new SearchCountryPojo("SawMiller"));
        postArrayList.add(new SearchCountryPojo("Scaffolder"));
        postArrayList.add(new SearchCountryPojo("SchoolCrossing"));
        postArrayList.add(new SearchCountryPojo("SchoolInspector"));
        postArrayList.add(new SearchCountryPojo("ScientificOfficer"));
        postArrayList.add(new SearchCountryPojo("Scientist"));
        postArrayList.add(new SearchCountryPojo("ScrapDealer"));
        postArrayList.add(new SearchCountryPojo("ScreenPrinter"));
        postArrayList.add(new SearchCountryPojo("ScreenWriter"));
        postArrayList.add(new SearchCountryPojo("ScriptWriter"));
        postArrayList.add(new SearchCountryPojo("Sculptor"));
        postArrayList.add(new SearchCountryPojo("Seaman"));
        postArrayList.add(new SearchCountryPojo("Seamstress"));
        postArrayList.add(new SearchCountryPojo("Secretary"));
        postArrayList.add(new SearchCountryPojo("SecurityConsultant"));
        postArrayList.add(new SearchCountryPojo("SecurityController"));
        postArrayList.add(new SearchCountryPojo("SecurityGuard"));
        postArrayList.add(new SearchCountryPojo("SecurityOfficer"));
        postArrayList.add(new SearchCountryPojo("Servant"));
        postArrayList.add(new SearchCountryPojo("ServiceEngineer"));
        postArrayList.add(new SearchCountryPojo("ServiceManager"));
        postArrayList.add(new SearchCountryPojo("ShareDealer"));
        postArrayList.add(new SearchCountryPojo("SheetMetalWorker"));
        postArrayList.add(new SearchCountryPojo("ShelfFiller"));
        postArrayList.add(new SearchCountryPojo("ShelterWarden"));
        postArrayList.add(new SearchCountryPojo("Shepherd"));
        postArrayList.add(new SearchCountryPojo("Sheriff"));
        postArrayList.add(new SearchCountryPojo("SheriffClerk"));
        postArrayList.add(new SearchCountryPojo("SheriffPrincipal"));
        postArrayList.add(new SearchCountryPojo("ShiftController"));
        postArrayList.add(new SearchCountryPojo("ShipBroker"));
        postArrayList.add(new SearchCountryPojo("ShipBuilder"));
        postArrayList.add(new SearchCountryPojo("ShippingClerk"));
        postArrayList.add(new SearchCountryPojo("ShippingOfficer"));
        postArrayList.add(new SearchCountryPojo("Shipwright"));
        postArrayList.add(new SearchCountryPojo("ShipyardWorker"));
        postArrayList.add(new SearchCountryPojo("ShoeMaker"));
        postArrayList.add(new SearchCountryPojo("ShoeRepairer"));
        postArrayList.add(new SearchCountryPojo("ShootingInstructor"));
        postArrayList.add(new SearchCountryPojo("ShopAssistant"));
        postArrayList.add(new SearchCountryPojo("ShopFitter"));
        postArrayList.add(new SearchCountryPojo("ShopKeeper"));
        postArrayList.add(new SearchCountryPojo("ShopManager"));
        postArrayList.add(new SearchCountryPojo("ShopProprietor"));
        postArrayList.add(new SearchCountryPojo("ShotBlaster"));
        postArrayList.add(new SearchCountryPojo("ShowJumper"));
        postArrayList.add(new SearchCountryPojo("Showman"));
        postArrayList.add(new SearchCountryPojo("Shunter"));
        postArrayList.add(new SearchCountryPojo("SignMaker"));
        postArrayList.add(new SearchCountryPojo("Signalman"));
        postArrayList.add(new SearchCountryPojo("Signwriter"));
        postArrayList.add(new SearchCountryPojo("SiteAgent"));
        postArrayList.add(new SearchCountryPojo("SiteEngineer"));
        postArrayList.add(new SearchCountryPojo("Skipper"));
        postArrayList.add(new SearchCountryPojo("Slater"));
        postArrayList.add(new SearchCountryPojo("Slaughterman"));
        postArrayList.add(new SearchCountryPojo("Smallholder"));
        postArrayList.add(new SearchCountryPojo("SocialWorker"));
        postArrayList.add(new SearchCountryPojo("SoftwareConsultant"));
        postArrayList.add(new SearchCountryPojo("SoftwareEngineer"));
        postArrayList.add(new SearchCountryPojo("Soldier"));
        postArrayList.add(new SearchCountryPojo("Solicitor"));
        postArrayList.add(new SearchCountryPojo("SongWriter"));
        postArrayList.add(new SearchCountryPojo("SoundArtist"));
        postArrayList.add(new SearchCountryPojo("SoundEngineer"));
        postArrayList.add(new SearchCountryPojo("SoundTechnician"));
        postArrayList.add(new SearchCountryPojo("SpecialConstable"));
        postArrayList.add(new SearchCountryPojo("SpecialNeeds"));
        postArrayList.add(new SearchCountryPojo("SpeechTherapist"));
        postArrayList.add(new SearchCountryPojo("SportsAdministrator"));
        postArrayList.add(new SearchCountryPojo("SportsCoach"));
        postArrayList.add(new SearchCountryPojo("SportsCommentator"));
        postArrayList.add(new SearchCountryPojo("Sportsman"));
        postArrayList.add(new SearchCountryPojo("Sportsperson"));
        postArrayList.add(new SearchCountryPojo("Sportswoman"));
        postArrayList.add(new SearchCountryPojo("SpringMaker"));
        postArrayList.add(new SearchCountryPojo("StableHand"));
        postArrayList.add(new SearchCountryPojo("StaffNurse"));
        postArrayList.add(new SearchCountryPojo("StageDirector"));
        postArrayList.add(new SearchCountryPojo("StageHand"));
        postArrayList.add(new SearchCountryPojo("StageManager"));
        postArrayList.add(new SearchCountryPojo("StageMover"));
        postArrayList.add(new SearchCountryPojo("StationManager"));
        postArrayList.add(new SearchCountryPojo("Stationer"));
        postArrayList.add(new SearchCountryPojo("Statistician"));
        postArrayList.add(new SearchCountryPojo("SteelErector"));
        postArrayList.add(new SearchCountryPojo("SteelWorker"));
        postArrayList.add(new SearchCountryPojo("Steeplejack"));
        postArrayList.add(new SearchCountryPojo("Stenographer"));
        postArrayList.add(new SearchCountryPojo("Steward"));
        postArrayList.add(new SearchCountryPojo("Stewardess"));
        postArrayList.add(new SearchCountryPojo("StockController"));
        postArrayList.add(new SearchCountryPojo("StockManager"));
        postArrayList.add(new SearchCountryPojo("Stockbroker"));
        postArrayList.add(new SearchCountryPojo("Stockman"));
        postArrayList.add(new SearchCountryPojo("Stocktaker"));
        postArrayList.add(new SearchCountryPojo("StoneCutter"));
        postArrayList.add(new SearchCountryPojo("StoneSawyer"));
        postArrayList.add(new SearchCountryPojo("Stonemason"));
        postArrayList.add(new SearchCountryPojo("StoreDetective"));
        postArrayList.add(new SearchCountryPojo("Storeman"));
        postArrayList.add(new SearchCountryPojo("Storewoman"));
        postArrayList.add(new SearchCountryPojo("StreetEntertainer"));
        postArrayList.add(new SearchCountryPojo("StreetTrader"));
        postArrayList.add(new SearchCountryPojo("StudHand"));
        postArrayList.add(new SearchCountryPojo("Student"));
        postArrayList.add(new SearchCountryPojo("StudentNurse"));
        postArrayList.add(new SearchCountryPojo("StudentTeacher"));
        postArrayList.add(new SearchCountryPojo("StudioManager"));
        postArrayList.add(new SearchCountryPojo("Sub-Postmaster"));
        postArrayList.add(new SearchCountryPojo("Sub-Postmistress"));
        postArrayList.add(new SearchCountryPojo("Supervisor"));
        postArrayList.add(new SearchCountryPojo("SupplyTeacher"));
        postArrayList.add(new SearchCountryPojo("Surgeon"));
        postArrayList.add(new SearchCountryPojo("Surveyor"));
        postArrayList.add(new SearchCountryPojo("SystemsAnalyst"));
        postArrayList.add(new SearchCountryPojo("SystemsEngineer"));
        postArrayList.add(new SearchCountryPojo("SystemsManager"));
        postArrayList.add(new SearchCountryPojo("TVEditor"));
        postArrayList.add(new SearchCountryPojo("TachographAnalyst"));
        postArrayList.add(new SearchCountryPojo("Tacker"));
        postArrayList.add(new SearchCountryPojo("Tailor"));
        postArrayList.add(new SearchCountryPojo("TankFarmOperative"));
        postArrayList.add(new SearchCountryPojo("TankerDriver"));
        postArrayList.add(new SearchCountryPojo("Tanner"));
        postArrayList.add(new SearchCountryPojo("Tattooist"));
        postArrayList.add(new SearchCountryPojo("TaxAdvisor"));
        postArrayList.add(new SearchCountryPojo("TaxAnalyst"));
        postArrayList.add(new SearchCountryPojo("TaxAssistant"));
        postArrayList.add(new SearchCountryPojo("TaxConsultant"));
        postArrayList.add(new SearchCountryPojo("TaxInspector"));
        postArrayList.add(new SearchCountryPojo("TaxManager"));
        postArrayList.add(new SearchCountryPojo("TaxOfficer"));
        postArrayList.add(new SearchCountryPojo("TaxiController"));
        postArrayList.add(new SearchCountryPojo("TaxiDriver"));
        postArrayList.add(new SearchCountryPojo("Taxidermist"));
        postArrayList.add(new SearchCountryPojo("TeaBlender"));
        postArrayList.add(new SearchCountryPojo("TeaTaster"));
        postArrayList.add(new SearchCountryPojo("Teacher"));
        postArrayList.add(new SearchCountryPojo("TeachersAssistant"));
        postArrayList.add(new SearchCountryPojo("TechnicalAdvisor"));
        postArrayList.add(new SearchCountryPojo("TechnicalAnalyst"));
        postArrayList.add(new SearchCountryPojo("TechnicalAssistant"));
        postArrayList.add(new SearchCountryPojo("TechnicalAuthor"));
        postArrayList.add(new SearchCountryPojo("TechnicalClerk"));
        postArrayList.add(new SearchCountryPojo("TechnicalCo-ordinator"));
        postArrayList.add(new SearchCountryPojo("TechnicalDirector"));
        postArrayList.add(new SearchCountryPojo("TechnicalEditor"));
        postArrayList.add(new SearchCountryPojo("TechnicalEngineer"));
        postArrayList.add(new SearchCountryPojo("TechnicalIllustrator"));
        postArrayList.add(new SearchCountryPojo("TechnicalInstructor"));
        postArrayList.add(new SearchCountryPojo("TechnicalLiaison"));
        postArrayList.add(new SearchCountryPojo("TechnicalManager"));
        postArrayList.add(new SearchCountryPojo("Technician"));
        postArrayList.add(new SearchCountryPojo("Telecommunication"));
        postArrayList.add(new SearchCountryPojo("Telecommunications"));
        postArrayList.add(new SearchCountryPojo("Telegraphist"));
        postArrayList.add(new SearchCountryPojo("Telemarketeer"));
        postArrayList.add(new SearchCountryPojo("TelephoneEngineer"));
        postArrayList.add(new SearchCountryPojo("Telephonist"));
        postArrayList.add(new SearchCountryPojo("TelesalesPerson"));
        postArrayList.add(new SearchCountryPojo("TelevisionDirector"));
        postArrayList.add(new SearchCountryPojo("TelevisionEngineer"));
        postArrayList.add(new SearchCountryPojo("TelevisionPresenter"));
        postArrayList.add(new SearchCountryPojo("TelevisionProducer"));
        postArrayList.add(new SearchCountryPojo("TelexOperator"));
        postArrayList.add(new SearchCountryPojo("TemperatureTime"));
        postArrayList.add(new SearchCountryPojo("TennisCoach"));
        postArrayList.add(new SearchCountryPojo("TextileConsultant"));
        postArrayList.add(new SearchCountryPojo("TextileEngineer"));
        postArrayList.add(new SearchCountryPojo("TextileTechnician"));
        postArrayList.add(new SearchCountryPojo("TextileWorker"));
        postArrayList.add(new SearchCountryPojo("Thatcher"));
        postArrayList.add(new SearchCountryPojo("TheatreManager"));
        postArrayList.add(new SearchCountryPojo("TheatreTechnician"));
        postArrayList.add(new SearchCountryPojo("TheatricalAgent"));
        postArrayList.add(new SearchCountryPojo("Therapist"));
        postArrayList.add(new SearchCountryPojo("ThermalEngineer"));
        postArrayList.add(new SearchCountryPojo("ThermalInsulator"));
        postArrayList.add(new SearchCountryPojo("TicketAgent"));
        postArrayList.add(new SearchCountryPojo("TicketInspector"));
        postArrayList.add(new SearchCountryPojo("Tiler"));
        postArrayList.add(new SearchCountryPojo("TimberInspector"));
        postArrayList.add(new SearchCountryPojo("TimberWorker"));
        postArrayList.add(new SearchCountryPojo("Tobacconist"));
        postArrayList.add(new SearchCountryPojo("TollCollector"));
        postArrayList.add(new SearchCountryPojo("ToolMaker"));
        postArrayList.add(new SearchCountryPojo("TourAgent"));
        postArrayList.add(new SearchCountryPojo("TourGuide"));
        postArrayList.add(new SearchCountryPojo("TownClerk"));
        postArrayList.add(new SearchCountryPojo("TownPlanner"));
        postArrayList.add(new SearchCountryPojo("ToyMaker"));
        postArrayList.add(new SearchCountryPojo("ToyTrader"));
        postArrayList.add(new SearchCountryPojo("TrackWorker"));
        postArrayList.add(new SearchCountryPojo("TractorDriver"));
        postArrayList.add(new SearchCountryPojo("TractorMechanic"));
        postArrayList.add(new SearchCountryPojo("TradeMarkAgent"));
        postArrayList.add(new SearchCountryPojo("TradeUnionOfficial"));
        postArrayList.add(new SearchCountryPojo("TradingStandards"));
        postArrayList.add(new SearchCountryPojo("TrafficWarden"));
        postArrayList.add(new SearchCountryPojo("TrainDriver"));
        postArrayList.add(new SearchCountryPojo("TraineeManager"));
        postArrayList.add(new SearchCountryPojo("TrainingAdvisor"));
        postArrayList.add(new SearchCountryPojo("TrainingAssistant"));
        postArrayList.add(new SearchCountryPojo("TrainingCo-ordinator"));
        postArrayList.add(new SearchCountryPojo("TrainingConsultant"));
        postArrayList.add(new SearchCountryPojo("TrainingInstructor"));
        postArrayList.add(new SearchCountryPojo("TrainingManager"));
        postArrayList.add(new SearchCountryPojo("TrainingOfficer"));
        postArrayList.add(new SearchCountryPojo("Transcriber"));
        postArrayList.add(new SearchCountryPojo("Translator"));
        postArrayList.add(new SearchCountryPojo("TransportClerk"));
        postArrayList.add(new SearchCountryPojo("TransportConsultant"));
        postArrayList.add(new SearchCountryPojo("TransportController"));
        postArrayList.add(new SearchCountryPojo("TransportEngineer"));
        postArrayList.add(new SearchCountryPojo("TransportManager"));
        postArrayList.add(new SearchCountryPojo("TransportOfficer"));
        postArrayList.add(new SearchCountryPojo("TransportPlanner"));
        postArrayList.add(new SearchCountryPojo("TravelAgent"));
        postArrayList.add(new SearchCountryPojo("TravelClerk"));
        postArrayList.add(new SearchCountryPojo("TravelConsultant"));
        postArrayList.add(new SearchCountryPojo("TravelCourier"));
        postArrayList.add(new SearchCountryPojo("TravelGuide"));
        postArrayList.add(new SearchCountryPojo("TravelGuideWriter"));
        postArrayList.add(new SearchCountryPojo("TravelRepresentative"));
        postArrayList.add(new SearchCountryPojo("TravellingShowman"));
        postArrayList.add(new SearchCountryPojo("Treasurer"));
        postArrayList.add(new SearchCountryPojo("TreeFeller"));
        postArrayList.add(new SearchCountryPojo("TreeSurgeon"));
        postArrayList.add(new SearchCountryPojo("Trichologist"));
        postArrayList.add(new SearchCountryPojo("TrinityHousePilot"));
        postArrayList.add(new SearchCountryPojo("TroutFarmer"));
        postArrayList.add(new SearchCountryPojo("TugSkipper"));
        postArrayList.add(new SearchCountryPojo("Tunneller"));
        postArrayList.add(new SearchCountryPojo("TurfAccountant"));
        postArrayList.add(new SearchCountryPojo("TurkeyFarmer"));
        postArrayList.add(new SearchCountryPojo("Turner"));
        postArrayList.add(new SearchCountryPojo("Tutor"));
        postArrayList.add(new SearchCountryPojo("Typesetter"));
        postArrayList.add(new SearchCountryPojo("TypewriterEngineer"));
        postArrayList.add(new SearchCountryPojo("Typist"));
        postArrayList.add(new SearchCountryPojo("TyreBuilder"));
        postArrayList.add(new SearchCountryPojo("TyreFitter"));
        postArrayList.add(new SearchCountryPojo("TyreInspector"));
        postArrayList.add(new SearchCountryPojo("TyreTechnician"));
        postArrayList.add(new SearchCountryPojo("Undertaker"));
        postArrayList.add(new SearchCountryPojo("Underwriter"));
        postArrayList.add(new SearchCountryPojo("Upholsterer"));
        postArrayList.add(new SearchCountryPojo("Valuer"));
        postArrayList.add(new SearchCountryPojo("ValveTechnician"));
        postArrayList.add(new SearchCountryPojo("VanDriver"));
        postArrayList.add(new SearchCountryPojo("VehicleAssessor"));
        postArrayList.add(new SearchCountryPojo("VehicleBodyWorker"));
        postArrayList.add(new SearchCountryPojo("VehicleEngineer"));
        postArrayList.add(new SearchCountryPojo("VehicleTechnician"));
        postArrayList.add(new SearchCountryPojo("Ventriloquist"));
        postArrayList.add(new SearchCountryPojo("Verger"));
        postArrayList.add(new SearchCountryPojo("VeterinarySurgeon"));
        postArrayList.add(new SearchCountryPojo("Vicar"));
        postArrayList.add(new SearchCountryPojo("VideoArtist"));
        postArrayList.add(new SearchCountryPojo("ViolinMaker"));
        postArrayList.add(new SearchCountryPojo("Violinist"));
        postArrayList.add(new SearchCountryPojo("VoluntaryWorker"));
        postArrayList.add(new SearchCountryPojo("WagesClerk"));
        postArrayList.add(new SearchCountryPojo("Waiter"));
        postArrayList.add(new SearchCountryPojo("Waitress"));
        postArrayList.add(new SearchCountryPojo("Warden"));
        postArrayList.add(new SearchCountryPojo("WarehouseManager"));
        postArrayList.add(new SearchCountryPojo("Warehouseman"));
        postArrayList.add(new SearchCountryPojo("Warehousewoman"));
        postArrayList.add(new SearchCountryPojo("Watchmaker"));
        postArrayList.add(new SearchCountryPojo("Weaver"));
        postArrayList.add(new SearchCountryPojo("WeighbridgeClerk"));
        postArrayList.add(new SearchCountryPojo("WeighbridgeOperator"));
        postArrayList.add(new SearchCountryPojo("Welder"));
        postArrayList.add(new SearchCountryPojo("WelfareAssistant"));
        postArrayList.add(new SearchCountryPojo("WelfareOfficer"));
        postArrayList.add(new SearchCountryPojo("WelfareRightsOfficer"));
        postArrayList.add(new SearchCountryPojo("WheelClamper"));
        postArrayList.add(new SearchCountryPojo("WholesaleNewspaper"));
        postArrayList.add(new SearchCountryPojo("WindowCleaner"));
        postArrayList.add(new SearchCountryPojo("WindowDresser"));
        postArrayList.add(new SearchCountryPojo("WindscreenFitter"));
        postArrayList.add(new SearchCountryPojo("WineMerchant"));
        postArrayList.add(new SearchCountryPojo("WoodCarver"));
        postArrayList.add(new SearchCountryPojo("WoodCutter"));
        postArrayList.add(new SearchCountryPojo("WoodWorker"));
        postArrayList.add(new SearchCountryPojo("WordProcessingOperator"));
        postArrayList.add(new SearchCountryPojo("WorksManager"));
        postArrayList.add(new SearchCountryPojo("Writer"));
        postArrayList.add(new SearchCountryPojo("YachtMaster"));
        postArrayList.add(new SearchCountryPojo("YardManager"));
        postArrayList.add(new SearchCountryPojo("YouthHostelWarden"));
        postArrayList.add(new SearchCountryPojo("YouthWorker"));
        postArrayList.add(new SearchCountryPojo("ZooKeeper"));
        postArrayList.add(new SearchCountryPojo("ZooManager"));
        postArrayList.add(new SearchCountryPojo("Zoologist"));



        myAppAdapter=new MyAppAdapter(postArrayList,SearchProfestion.this);
        listView.setAdapter(myAppAdapter);



        listView.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {

//                    Toast.makeText(SearchActivity.this, "This is my Toast message!"+position+"",
//                            Toast.LENGTH_LONG).show();
                    TextView chidtext = (TextView) view.findViewById(R.id.title);
                     value = chidtext.getText().toString();
                FragmentCountryList.ProfestionLink(value);
                Intent opencountrylist = new Intent(SearchProfestion.this,FragmentCountryList.class);
//                opencountrylist.putExtra("ProfestionValue",value);
                startActivity(opencountrylist);







            }
        });





    }

    public class MyAppAdapter extends BaseAdapter {

        public class ViewHolder {
            TextView txtTitle,txtSubTitle;
        }

        public List<SearchCountryPojo> parkingList;
        public Context context;
        ArrayList<SearchCountryPojo> arraylist;

        private MyAppAdapter(List<SearchCountryPojo> apps, Context context) {
            this.parkingList = apps;
            this.context = context;
            arraylist = new ArrayList<SearchCountryPojo>();
            arraylist.addAll(parkingList);

        }

        @Override
        public int getCount() {
            return parkingList.size();
        }

        @Override
        public Object getItem(int position) {
            return position;
        }

        @Override
        public long getItemId(int position) {
            return position;
        }

        @Override
        public View getView(final int position, View convertView, ViewGroup parent) {

            View rowView = convertView;
            ViewHolder viewHolder;

            if (rowView == null) {
                LayoutInflater inflater = getLayoutInflater();
                rowView = inflater.inflate(R.layout.search_country_item, null);
                // configure view holder
                viewHolder = new ViewHolder();
                viewHolder.txtTitle = (TextView) rowView.findViewById(R.id.title);
//                viewHolder.txtSubTitle = (TextView) rowView.findViewById(R.id.subtitle);
                rowView.setTag(viewHolder);

            } else {
                viewHolder = (ViewHolder) convertView.getTag();
            }

            viewHolder.txtTitle.setText(parkingList.get(position).getPostTitle() + "");
//            viewHolder.txtSubTitle.setText(parkingList.get(position).getPostSubTitle() + "");
            return rowView;
        }

        public void filter(String charText) {

            charText = charText.toLowerCase(Locale.getDefault());

            parkingList.clear();
            if (charText.length() == 0) {
                parkingList.addAll(arraylist);

            } else {
                for (SearchCountryPojo postDetail : arraylist) {
                    if (charText.length() != 0 && postDetail.getPostTitle().toLowerCase(Locale.getDefault()).contains(charText)) {
                        parkingList.add(postDetail);
                    }

//                    else if (charText.length() != 0 && postDetail.getPostSubTitle().toLowerCase(Locale.getDefault()).contains(charText)) {
//                        parkingList.add(postDetail);
//                    }
                }
            }
            notifyDataSetChanged();
        }
    }


    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        getMenuInflater().inflate(R.menu.menu_search, menu);
        MenuItem searchItem = menu.findItem(R.id.action_search);
        SearchView searchView = (SearchView) MenuItemCompat.getActionView(searchItem);
        //*** setOnQueryTextFocusChangeListener ***
        searchView.setOnQueryTextFocusChangeListener(new View.OnFocusChangeListener() {

            @Override
            public void onFocusChange(View v, boolean hasFocus) {

            }
        });

        searchView.setOnQueryTextListener(new SearchView.OnQueryTextListener() {

            @Override
            public boolean onQueryTextSubmit(String query) {

                return false;
            }
            @Override
            public boolean onQueryTextChange(String searchQuery) {
                myAppAdapter.filter(searchQuery.toString().trim());
                listView.invalidate();
                return true;
            }
        });

        MenuItemCompat.setOnActionExpandListener(searchItem, new MenuItemCompat.OnActionExpandListener() {
            @Override
            public boolean onMenuItemActionCollapse(MenuItem item) {
                // Do something when collapsed
                return true;  // Return true to collapse action view
            }
            @Override
            public boolean onMenuItemActionExpand(MenuItem item) {
                // Do something when expanded
                return true;  // Return true to expand action view
            }
        });
        return true;
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        // Handle action bar item clicks here. The action bar will
        // automatically handle clicks on the Home/Up button, so long
        // as you specify a parent activity in AndroidManifest.xml.
        int id = item.getItemId();

        //noinspection SimplifiableIfStatement
        if (id == R.id.action_search) {
            return true;
        }
        return super.onOptionsItemSelected(item);
    }



}
